	  ORG 0500H

          MOV SI,1100H	;SI IS POINTER FOR ARRAY
	  MOV DI,1200H	;LOAD ADDRESS OF DATA
	  MOV DL,[DI]	;GET THE DATA 
	  MOV BL,01H	;BL REGISTER FOR POSITION COUNT
	  MOV AL,[SI]	;GET FIRST ELEMENT OF ARRAY IN AL REGISTER

START:	  CMP AL,DL	
	  JZ INCLUDE
	  INC SI	;INCREMENT ADDRESS PONTER
	  INC BL	;INCREMENT POSITION COUNT
	  MOV AL,[SI]	;GET NEXT ELEMENT OF ARRAY
	  CMP AL,20H	;CHECK FOR END OF ARRAY
	  JNZ START

NODATA:	  MOV CX,0000H
	  MOV [DI+1],CX
	  MOV [DI+3],CX
	  JMP END

INCLUDE:  MOV BH,0FFH
	  MOV [DI+1],BH
	  MOV [DI+2],BL	;STORE THE POSITION OF DATA
	  MOV [DI+3],SI	;STORE THE ADDRESS OF DATA

END: HLT