;PROGRAM IN 8086 MP SORT IN ASCENDING ORDER
;SIZE OF AN ARRAY STORED AT MEMORY ADDRESS 100:1000 
;NUMBERS ARE STORED FROM MEMORY ADDRESS  100:1202
	  ORG 0300

	  MOV SI,1200h
	  MOV CL,[SI]
	  DEC CL

LOOP3:	  MOV SI,1200h
	  MOV CH,[SI]
  	  DEC CH
	  INC SI

LOOP2:	  MOV AL,[SI] 
	  INC SI
	  CMP AL,[SI]
	  JC LOOP1
	  XCHG AL,[SI]
	  XCHG [SI-1],AL

LOOP1:	  DEC CH 
	  JNZ LOOP2
	  DEC CL
	  JNZ LOOP3
  	  HLT