;this source code written for PAT microcomputer system which uses 80286 inter microprocessor
;D2000 development system assembler can be use to convert this source code to an executable machine code program

		  INCLUDE PATCALLS.INC
	  ORG 0500H

INT25V    EQU 094H
UMODREG   EQU 086H	;PAT ENCODES MODE REGISTER PORT ADDRESS AS 086H
UPORT1CTL EQU 088H	;PAT ENCODES PORT1 CONTROL REGISTER PORT ADDRESS AS 088H
UPORT1    EQU 090H	;PAT ENCODES PORT1 PORT ADDRESS AS 090H
UPORT2    EQU 092H	;PAT ENCODES PORT2 PORT ADDRESS AS 092H

;DISABLE INTERRUPTS 
	  CLI 
;SET UP INTERRUPT VECTORS
	  MOV DX,DS
	  MOV AX,0000H
	  MOV DS,AX
	  MOV WORD PTR DS:INT25V,0300H
	  MOV WORD PTR DS:INT25V + 2,0080H
;INITIALIZE TIMER
	  MOV AL,03H
	  OUT UCRREGI,AL
	  MOV AL,0FAH
	  OUT UTIMER1,AL
	  MOV AL,01H
	  OUT UIRGEN,AL
	  MOV DX,00H
 		
	  STI

START:	  MOV AL,00H	;MOD REG. PC0 = 0,PC1 = 0,PC2 = 0 SO PORT 2 BOTH NIBBLES CONFIGURED AS INPUT 
	  OUT UMODREG,AL

	  MOV AL,BL	;P10 = 1,P12 = 0,P13 = 1,P11 = 1
	  OUT UPORT1CTL,AL

;GENERATE SHORT NEGATIVE GOING PULSE ON P11 TO INITIATE CONVERSION
	  MOV AL,02H
	  OUT UPORT1,AL

	  MOV AL,00H
	  OUT UPORT1,AL

	  MOV AL,02H
	  OUT UPORT1,AL

;MONITOR P12 & WAIT UNTIL P12 = 1
CHECK:    IN AL,UPORT1
	  TEST AL,04H
	  JNZ CHECK

;ENABLE ADC & READ POTENTIOMETER VALUE
	  MOV AL,0F7H
	  OUT UPORT1,AL

	  IN AL,UPORT2
	  MOV BL,AL

	  MOV AL,08H
	  OUT UPORT1,AL
;DAC PART 
	  MOV AL,00H
	  OUT UPORT1,AL		;OUTPUT LOGIC 0 ON P10 TO ENABLE DAC

	  MOV AL,03H
	  OUT UMODREG,AL

	  OUT UPORT2,BL

	  PUSH CX
	  MOV CX,0FFFH
DLY:      LOOP DLY
	  POP CX

HERE: JUMP HERE

	  JUMP START


	  ORG 0200H
	  IN AL,UIRQADR		;CLEAR INTERRUPT FLAGS

	  MOV AL,0FAH	        ;RE-LOAD TIMER DELAY VALUE
	  OUT UTIMER,AL
	  MOV AL,01H	        ;RE-ENABLE INTERRUPTS FROM TIMER 
	  OUT UIRCEN,AL

ADD:	 IN AL,PORT1
	 TEST AL,10H
	 JZ ADD
	 CALL WAITDSC

	 MOV AL,20H	;NON SPECIFIC END OF INTERRUPT
	 OUT 40H,AL	;RETURN TO MAIN 
	 IRET




WAITDSC:  INC DX
CHECKDSC: IN AL,PORT1
	  TEST AL,10H
	  JNZ CHECKDSC
	  RET
















