;this source code written for PAT microcomputer system which uses 80286 inter microprocessor
;D2000 development system assembler can be use to convert this source code to an executable machine code program

	  ORG 0200H

UMODREG   EQU 086H	;PAT MICROCOMPUTER SYSTEM ENCODES MOD REGISTER PORT ADRESS AS 086H
UPORT1CTL EQU 088H	;PAT MICROCOMPUTER SYSTEM ENCODES PORT1 CONTROL REGISTER PORT ADRESS AS 088H
UPORT1    EQU 090H	;PAT MICROCOMPUTER SYSTEM ENCODES PORT1 PORT ADRESS AS 090H
UPORT2    EQU 092H	;PAT MICROCOMPUTER SYSTEM ENCODES PORT2 PORT ADRESS AS 086H

	  MOV AL,40H
	  OUT UPORT1CTL,AL

	  MOV AL,03H
	  OUT UMODREG,AL ;CONFIGURE PORT2 AS ALL OUTPUT 

	  MOV AL,40H
	  OUT UPORT1,AL

DETECT:  IN AL,UPORT1
	 TEST AL,80H
	 JZ DETECT

	 MOV AL,0FFH
	 OUT UPORT2,AL

	 JMP DETECT

